// The routine tool schemas (asgard-upgrade Phase 3.2). Kept import-free so
// tools.js can append them to the master order at evaluation time.
export const ROUTINE_TOOL_DEFINITIONS = [
  { name: 'routine_create', description: "Create a routine from what Rayan asked for: a schedule ({kind:'schedule', at:'07:00', days:[1,2,3,4,5], tz:'America/Los_Angeles'} or {kind:'schedule', every:30}) or an event ({kind:'event', event:'watchlist.hit'}), an ordered list of steps ({tool,args} | {delegate:{councillor,task}} | {compose:{instruction,tier:'cheap'|'owner'}} | {read:'calendar'|'timers'|'todos'|'activity'|'memory'|'council'|'health'|'paper'} | {say:'text'}; args may reference $steps[0].text, $event.payload.x, $date.today, $date.tomorrow), and how to deliver ('telegram' default, 'notify', 'speak', 'silent'). FIRST call WITHOUT confirmed: it returns the one-sentence read-back; say that to Rayan; once he agrees call again with confirmed: true. Events you can trigger on: watchlist.hit, monitor.changed, timer.done, calendar.upcoming, telegram.message, paper.trade.opened, paper.trade.closed, paper.report.sent, extension.offline, extension.online, kv.quota.warning, councillor.finished, approval.created, approval.resolved, clip.posted, hall.opened.",
    input_schema: { type: 'object', properties: { name: { type: 'string' }, intent: { type: 'string', description: 'one sentence, what it is for' }, trigger: { type: 'object' }, steps: { type: 'array', items: { type: 'object' } }, deliver: { type: 'string', enum: ['telegram', 'notify', 'speak', 'silent'] }, confirmed: { type: 'boolean' } }, required: ['name', 'trigger', 'steps'] } },
  { name: 'routine_list', description: 'List your routines: what they do, when, and their last run.', input_schema: { type: 'object', properties: {} } },
  { name: 'routine_pause', description: 'Pause one of your routines by name.', input_schema: { type: 'object', properties: { match: { type: 'string' } }, required: ['match'] } },
  { name: 'routine_resume', description: 'Resume a paused routine by name.', input_schema: { type: 'object', properties: { match: { type: 'string' } }, required: ['match'] } },
  { name: 'routine_delete', description: 'Delete one of your routines by name (its record is kept, marked deleted).', input_schema: { type: 'object', properties: { match: { type: 'string' } }, required: ['match'] } },
  { name: 'routine_run_now', description: 'Run one of your routines right now instead of waiting for its trigger.', input_schema: { type: 'object', properties: { match: { type: 'string' } }, required: ['match'] } },
  { name: 'routine_history', description: 'The last runs of one of your routines: when, ok or failed, delivered how.', input_schema: { type: 'object', properties: { match: { type: 'string' } }, required: ['match'] } }
];
