import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';
import {MODELS} from '../src/lib/models.js';import {capToolResult} from '../src/lib/tool-discovery.js';import {TOOL_DEFINITIONS} from '../src/lib/tools.js';import {gradeLatency} from '../evals/latency.mjs';import {consistency,gradeSelection} from '../evals/grade.mjs';
async function sources(dir){return(await Promise.all((await readdir(dir,{withFileTypes:true})).map(e=>e.isDirectory()?sources(`${dir}/${e.name}`):e.name.endsWith('.js')?readFile(`${dir}/${e.name}`,'utf8'):''))).flat().join('\n');}
test('model IDs and thinking budgets stay valid',async()=>{assert.equal(MODELS.sonnet,'claude-sonnet-5');assert.equal(MODELS.haiku,'claude-haiku-4-5-20251001');assert.doesNotMatch(await sources('src'),/budget_tokens\s*:\s*400\b/);});
test('Chrome companion retains current and fallback hosts',async()=>{const s=await readFile('background.js','utf8');for(const host of ['asgrard-backend.rayanfahil2.workers.dev','rayven-backend.rayanfahil2.workers.dev'])assert.ok(s.includes(host));});
test('image tool results remain images, while long text remains capped',()=>{const image={type:'image',source:{type:'base64',media_type:'image/jpeg',data:'fixture'}};const r=capToolResult([{type:'text',text:'a'.repeat(30000)},image]);assert.ok(Array.isArray(r));assert.deepEqual(r[1],image);assert.ok(r[0].text.length<8100);});
test('every provisional selection case references a real registered tool',async()=>{const cases=JSON.parse(await readFile('evals/tool-selection.json')).cases;assert.equal(cases.length,60);const names=new Set(TOOL_DEFINITIONS.map(t=>t.name));for(const c of cases)assert.ok(names.has(c.expected_tool),c.expected_tool);assert.throws(()=>gradeSelection(cases,[]),/BLOCKED/);});
test('latency gates reject missing or slow evidence; fixture data is not a benchmark',()=>{assert.throws(()=>gradeLatency([]),/BLOCKED/);const samples=Array.from({length:20},(_,i)=>({origin:'live',release:'fixture-only',sessionId:'fixture',turn:i%2+1,ttftMs:200,firstAudioMs:600,cache_read_input_tokens:100}));assert.equal(gradeLatency(samples).pass,true);samples[18].ttftMs=900;samples[19].ttftMs=900;assert.equal(gradeLatency(samples).pass,false);samples[19].firstAudioMs=null;assert.throws(()=>gradeLatency(samples),/BLOCKED/);});
test('consistency distinguishes occasional success from repeatable success',()=>{assert.deepEqual(consistency([{caseId:'a',pass:true},{caseId:'a',pass:false},{caseId:'b',pass:true},{caseId:'b',pass:true}],2),{cases:2,k:2,passAtK:1,passPowerK:0.5});assert.throws(()=>consistency([{caseId:'a',pass:true}],2));});
