// CATALOGUE — WORLD, WEATHER, SAFETY (asgard-upgrade Phase 7.3). Valkyrie, Sylvie.
// Bakersfield / Kern County matter here. No keys (NASA uses DEMO_KEY unless a key exists).
import { httpGet, httpJson, clip, capN, errorText, stripTags } from '../lib/http.js';
const S = (props, required = []) => ({ type: 'object', properties: props, required });
const str = d => ({ type: 'string', description: d }), int = d => ({ type: 'integer', description: d }), num = d => ({ type: 'number', description: d });
const enc = encodeURIComponent; const G = 'world';
const BAK = { lat: 35.3733, lon: -119.0187 };
const dist = (a, b, c, d) => { const R = 6371, dLat = (c - a) * Math.PI / 180, dLon = (d - b) * Math.PI / 180, x = Math.sin(dLat / 2) ** 2 + Math.cos(a * Math.PI / 180) * Math.cos(c * Math.PI / 180) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.sqrt(x)); };
const num2 = (v, d) => (typeof v === 'number' && isFinite(v) ? v : d);

export const TOOLS = [
  { name: 'nws_alerts', group: G, taint: true, description: 'Active National Weather Service alerts for a US state (area like CA) or a point (lat, lon). Kern County: use lat 35.37, lon -119.02.', input_schema: S({ area: str('two-letter state code, e.g. CA'), lat: num('latitude (with lon, instead of area)'), lon: num('longitude'), n: int('alerts, default 10, max 20') }),
    async run(env, { area, lat, lon, n }) { const q = lat != null && lon != null ? `point=${num2(lat, BAK.lat)},${num2(lon, BAK.lon)}` : `area=${enc((area || 'CA').toUpperCase().slice(0, 2))}`; const r = await httpJson(env, `https://api.weather.gov/alerts/active?${q}`, { accept: 'application/geo+json, application/json', cacheSeconds: 300 }); if (!r.ok) return errorText('nws_alerts', r); const f = (r.json || {}).features || []; if (!f.length) return `No active NWS alerts for ${lat != null ? 'that point' : (area || 'CA')}.`; return clip(f.slice(0, capN(n)).map((x, i) => { const p = x.properties || {}; return `${i + 1}. ${p.event} (${p.severity}, ${p.urgency}) — ${p.areaDesc}\n   ${p.headline || ''}${p.ends ? ` — until ${p.ends}` : ''}`; }).join('\n')); } },
  { name: 'nws_forecast', group: G, taint: true, description: 'NWS forecast for a US point: the next periods (name, temperature, wind, short forecast). Default is Bakersfield.', input_schema: S({ lat: num('latitude, default 35.37'), lon: num('longitude, default -119.02'), n: int('periods, default 6, max 14') }),
    async run(env, { lat, lon, n }) { const la = num2(lat, BAK.lat).toFixed(4), lo = num2(lon, BAK.lon).toFixed(4); const p = await httpJson(env, `https://api.weather.gov/points/${la},${lo}`, { accept: 'application/geo+json, application/json', cacheSeconds: 86400 }); if (!p.ok) return errorText('nws_forecast', p); const fu = ((p.json || {}).properties || {}).forecast; if (!fu) return 'nws_forecast: no forecast office for that point (US only).'; const f = await httpJson(env, fu, { accept: 'application/geo+json, application/json', cacheSeconds: 1800 }); if (!f.ok) return errorText('nws_forecast', f); const periods = (((f.json || {}).properties || {}).periods || []).slice(0, Math.min(14, capN(n, 6, 14))); return clip(`${((p.json || {}).properties || {}).relativeLocation ? (p.json.properties.relativeLocation.properties.city + ', ' + p.json.properties.relativeLocation.properties.state) : `${la},${lo}`}:\n` + periods.map(x => `${x.name}: ${x.temperature}°${x.temperatureUnit}, wind ${x.windSpeed} ${x.windDirection} — ${x.shortForecast}`).join('\n')); } },
  { name: 'quakes', group: G, taint: true, description: 'Recent earthquakes from USGS: minimum magnitude, past days, optionally near a place (default Bakersfield, 300 km).', input_schema: S({ minMag: num('minimum magnitude, default 2.5'), days: int('past days, default 7, max 20'), lat: num('centre latitude, default Bakersfield'), lon: num('centre longitude'), radiusKm: num('radius km, default 300'), n: int('results, default 10, max 20') }),
    async run(env, { minMag, days, lat, lon, radiusKm, n }) { const start = new Date(Date.now() - capN(days, 7) * 86400000).toISOString().slice(0, 10); const la = num2(lat, BAK.lat), lo = num2(lon, BAK.lon), rad = Math.min(2000, num2(radiusKm, 300)); const r = await httpJson(env, `https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=${start}&minmagnitude=${num2(minMag, 2.5)}&latitude=${la}&longitude=${lo}&maxradiuskm=${rad}&orderby=time&limit=${capN(n)}`, { cacheSeconds: 300 }); if (!r.ok) return errorText('quakes', r); const f = (r.json || {}).features || []; if (!f.length) return `No M${num2(minMag, 2.5)}+ earthquakes within ${rad} km in the last ${capN(days, 7)} days.`; return clip(f.map((x, i) => { const p = x.properties, [qlon, qlat, depth] = x.geometry.coordinates; return `${i + 1}. M${p.mag} ${p.place} — ${new Date(p.time).toISOString().replace('T', ' ').slice(0, 16)} UTC, depth ${Math.round(depth)} km, ${Math.round(dist(la, lo, qlat, qlon))} km away`; }).join('\n')); } },
  { name: 'calfire_incidents', group: G, taint: true, description: 'Active CAL FIRE incidents this year: name, county, acres, containment, updated. Optional county filter (default all; Kern for home).', input_schema: S({ county: str('county name filter, e.g. Kern'), n: int('incidents, default 10, max 20') }),
    async run(env, { county, n }) { const y = new Date().getFullYear(); const r = await httpJson(env, `https://incidents.fire.ca.gov/umbraco/api/IncidentApi/List?year=${y}`, { cacheSeconds: 900 }); if (!r.ok) return errorText('calfire_incidents', r); let list = Array.isArray(r.json) ? r.json : []; list = list.filter(x => x.IsActive !== false); if (county) list = list.filter(x => String(x.County || '').toLowerCase().includes(String(county).toLowerCase())); if (!list.length) return `No active CAL FIRE incidents${county ? ` in ${county}` : ''} listed for ${y}.`; list.sort((a, b) => String(b.Updated).localeCompare(String(a.Updated))); return clip(list.slice(0, capN(n)).map((x, i) => `${i + 1}. ${x.Name} — ${x.County} County, ${Number(x.AcresBurned || 0).toLocaleString('en-US')} acres, ${x.PercentContained != null ? x.PercentContained + '% contained' : 'containment ?'}, updated ${String(x.Updated).slice(0, 16)}${x.Url ? `\n   ${x.Url}` : ''}`).join('\n')); } },
  { name: 'space_weather', group: G, taint: true, description: 'Space weather from NOAA SWPC: the planetary K index (geomagnetic activity) for the last hours and any current alerts.', input_schema: S({}),
    async run(env) { const [k, a] = await Promise.all([httpJson(env, 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json', { cacheSeconds: 900 }), httpJson(env, 'https://services.swpc.noaa.gov/products/alerts.json', { cacheSeconds: 900 })]); if (!k.ok) return errorText('space_weather', k); const raw = Array.isArray(k.json) ? k.json : []; const rows = (raw.length && Array.isArray(raw[0]) ? raw.slice(1).map(r => ({ t: r[0], kp: r[1] })) : raw.map(r => ({ t: r.time_tag, kp: r.kp_index != null ? r.kp_index : r.Kp }))).slice(-6); const kp = rows.map(r => `${String(r.t || '').slice(11, 16)}Z Kp ${r.kp}`).join(', '); const alerts = a.ok ? (a.json || []).slice(0, 3).map(x => String(x.message || '').split('\n').find(l => /WATCH|WARNING|ALERT|SUMMARY/.test(l)) || '').filter(Boolean) : []; return `Planetary K index (last 6 readings): ${kp}. ${Number(rows[rows.length - 1] && rows[rows.length - 1].kp) >= 5 ? 'Geomagnetic storm conditions.' : 'Quiet to unsettled.'}${alerts.length ? ' Latest SWPC notices: ' + alerts.join(' | ') : ''}`; } },
  { name: 'iss_now', group: G, taint: true, description: 'Where the International Space Station is right now (latitude, longitude, altitude, speed) and how far from Bakersfield.', input_schema: S({}),
    async run(env) { const r = await httpJson(env, 'https://api.wheretheiss.at/v1/satellites/25544'); if (!r.ok) return errorText('iss_now', r); const j = r.json || {}; return `ISS: ${Number(j.latitude).toFixed(2)}, ${Number(j.longitude).toFixed(2)} at ${Math.round(j.altitude)} km, ${Math.round(j.velocity).toLocaleString('en-US')} km/h, ${j.visibility}; about ${Math.round(dist(BAK.lat, BAK.lon, j.latitude, j.longitude)).toLocaleString('en-US')} km from Bakersfield (ground track).`; } },
  { name: 'nasa_apod', group: G, taint: true, description: 'NASA\'s Astronomy Picture of the Day: title, explanation (short), and the image link. Uses NASA_API_KEY if set, else DEMO_KEY.', input_schema: S({ date: str('YYYY-MM-DD, optional') }),
    async run(env, { date }) { const key = env.NASA_API_KEY || 'DEMO_KEY'; const r = await httpJson(env, `https://api.nasa.gov/planetary/apod?api_key=${enc(key)}${date ? `&date=${enc(date)}` : ''}&thumbs=true`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('nasa_apod', r); const j = r.json || {}; return `${j.title} (${j.date}${j.copyright ? `, © ${String(j.copyright).trim()}` : ''})\n${String(j.explanation || '').slice(0, 600)}\n${j.url || j.thumbnail_url || ''}`; } },
  { name: 'tides', group: G, taint: true, description: 'Today\'s high and low tide predictions for a NOAA station id (e.g. 9410170 San Diego, 9410660 Los Angeles, 9414290 San Francisco).', input_schema: S({ station: str('NOAA station id') }, ['station']),
    async run(env, { station }) { const d = new Date(); const ymd = `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}${String(d.getUTCDate()).padStart(2, '0')}`; const r = await httpJson(env, `https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions&application=Asgard&begin_date=${ymd}&end_date=${ymd}&datum=MLLW&station=${enc(station)}&time_zone=lst_ldt&units=english&interval=hilo&format=json`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('tides', r); const p = (r.json || {}).predictions || []; if (!p.length) return `tides: no predictions for station ${station} (${(r.json && r.json.error && r.json.error.message) || 'check the id'}).`; return `Station ${station}, today (local): ` + p.map(x => `${x.type === 'H' ? 'High' : 'Low'} ${x.t.slice(11)} ${Number(x.v).toFixed(1)} ft`).join(' · '); } },
  { name: 'elevation', group: G, taint: true, description: 'Elevation in metres and feet for a latitude/longitude (Open Topo Data, SRTM 90 m).', input_schema: S({ lat: num('latitude'), lon: num('longitude') }, ['lat', 'lon']),
    async run(env, { lat, lon }) { const r = await httpJson(env, `https://api.opentopodata.org/v1/srtm90m?locations=${num2(lat, BAK.lat)},${num2(lon, BAK.lon)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('elevation', r); const e = (((r.json || {}).results || [])[0] || {}).elevation; return e == null ? 'elevation: no value for that point' : `Elevation at ${lat}, ${lon}: ${Math.round(e)} m (${Math.round(e * 3.28084)} ft).`; } },
  { name: 'zip_lookup', group: G, taint: true, description: 'US ZIP code → city, state, latitude, longitude (Zippopotam).', input_schema: S({ zip: str('5-digit ZIP') }, ['zip']),
    async run(env, { zip }) { const r = await httpJson(env, `https://api.zippopotam.us/us/${enc(String(zip).slice(0, 5))}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('zip_lookup', r); const p = ((r.json || {}).places || [])[0]; return p ? `${zip}: ${p['place name']}, ${p['state abbreviation']} (${p.latitude}, ${p.longitude})` : `No such ZIP ${zip}.`; } },
  { name: 'ip_geo', group: G, taint: true, description: 'Rough location and network for a public IP address (geojs.io).', input_schema: S({ ip: str('IPv4 or IPv6 address') }, ['ip']),
    async run(env, { ip }) { const r = await httpJson(env, `https://get.geojs.io/v1/ip/geo/${enc(String(ip).trim())}.json`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('ip_geo', r); const j = r.json || {}; return `${j.ip}: ${[j.city, j.region, j.country].filter(Boolean).join(', ')} — ${j.organization || j.organization_name || 'unknown network'} (${j.timezone || ''})`; } },
  { name: 'osm_search', group: G, taint: true, description: 'Find a place by name with OpenStreetMap Nominatim (free fallback behind Google Maps): display name and coordinates.', input_schema: S({ q: str('place or address'), n: int('results, default 3, max 10') }, ['q']),
    async run(env, { q, n }) { const r = await httpJson(env, `https://nominatim.openstreetmap.org/search?format=jsonv2&limit=${Math.min(10, capN(n, 3))}&q=${enc(q)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('osm_search', r); return clip((r.json || []).map((p, i) => `${i + 1}. ${p.display_name} (${Number(p.lat).toFixed(4)}, ${Number(p.lon).toFixed(4)}) [${p.type}]`).join('\n') || `Nothing found for ${q}.`); } },
  { name: 'osm_reverse', group: G, taint: true, description: 'Coordinates → the nearest address (OpenStreetMap Nominatim).', input_schema: S({ lat: num('latitude'), lon: num('longitude') }, ['lat', 'lon']),
    async run(env, { lat, lon }) { const r = await httpJson(env, `https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${num2(lat, BAK.lat)}&lon=${num2(lon, BAK.lon)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('osm_reverse', r); return (r.json || {}).display_name || 'No address there.'; } },
  { name: 'osm_nearby', group: G, taint: true, description: 'Places of a kind near a point via Overpass (OpenStreetMap): cafe, restaurant, pharmacy, fuel, park, hospital, library, atm… within a small radius.', input_schema: S({ what: str('kind, e.g. cafe, pharmacy, fuel, park'), lat: num('latitude, default Bakersfield'), lon: num('longitude'), r: num('radius in metres, default 800, max 3000'), n: int('results, default 10, max 20') }, ['what']),
    async run(env, { what, lat, lon, r, n }) { const la = num2(lat, BAK.lat), lo = num2(lon, BAK.lon), rad = Math.min(3000, num2(r, 800)); const kind = String(what || '').toLowerCase().replace(/[^a-z_]/g, ''); const q = `[out:json][timeout:8];(node["amenity"="${kind}"](around:${rad},${la},${lo});node["leisure"="${kind}"](around:${rad},${la},${lo});node["shop"="${kind}"](around:${rad},${la},${lo}););out ${capN(n)};`; let res = await httpJson(env, `https://overpass-api.de/api/interpreter?data=${enc(q)}`, { timeoutMs: 10000, cacheSeconds: 3600 }); if (!res.ok) res = await httpJson(env, `https://overpass.kumi.systems/api/interpreter?data=${enc(q)}`, { timeoutMs: 10000, cacheSeconds: 3600 }); if (!res.ok) return errorText('osm_nearby', res); const els = (res.json || {}).elements || []; if (!els.length) return `No ${kind} within ${rad} m.`; return clip(els.map((e, i) => `${i + 1}. ${(e.tags && e.tags.name) || `(unnamed ${kind})`}${e.tags && e.tags['addr:street'] ? ` — ${e.tags['addr:housenumber'] || ''} ${e.tags['addr:street']}` : ''} · ${Math.round(dist(la, lo, e.lat, e.lon) * 1000)} m`).join('\n')); } },
  { name: 'country_info', group: G, taint: true, description: 'Facts about a country: capital, region, income level and latest population (World Bank) plus a one-line summary (Wikipedia).', input_schema: S({ name: str('country name') }, ['name']),
    async run(env, { name }) { const q = String(name || '').trim().toLowerCase(); const list = await httpJson(env, 'https://api.worldbank.org/v2/country?format=json&per_page=400', { cacheSeconds: 86400, maxBytes: 1024 * 1024 }); if (!list.ok) return errorText('country_info', list); const all = Array.isArray(list.json) ? (list.json[1] || []) : []; const c = all.find(x => String(x.name).toLowerCase() === q || String(x.iso2Code).toLowerCase() === q || String(x.id).toLowerCase() === q) || all.find(x => String(x.name).toLowerCase().includes(q)); if (!c) return `No country called ${name} in the World Bank list.`; const [pop, wiki] = await Promise.all([httpJson(env, `https://api.worldbank.org/v2/country/${enc(c.id)}/indicator/SP.POP.TOTL?format=json&per_page=3`, { cacheSeconds: 86400 }), httpJson(env, `https://en.wikipedia.org/api/rest_v1/page/summary/${enc(String(c.name).replace(/ /g, '_'))}`, { cacheSeconds: 86400 })]); const pr = pop.ok && Array.isArray(pop.json) ? (pop.json[1] || []).find(x => x.value != null) : null; const ex = wiki.ok && wiki.json && wiki.json.extract ? String(wiki.json.extract).split('. ')[0] + '.' : ''; return `${c.name} (${c.iso2Code}): capital ${c.capitalCity || '?'}; ${(c.region || {}).value || ''}; ${(c.incomeLevel || {}).value || ''}${pr ? `; population ${Number(pr.value).toLocaleString('en-US')} (${pr.date})` : ''}. ${ex}`.replace(/\s+/g, ' '); } },
  { name: 'world_bank', group: G, taint: true, description: 'A World Bank indicator for a country, latest years: e.g. SP.POP.TOTL population, NY.GDP.MKTP.CD GDP (US$), FP.CPI.TOTL.ZG inflation, SL.UEM.TOTL.ZS unemployment.', input_schema: S({ indicator: str('indicator code'), country: str('ISO2/ISO3 code, e.g. US'), n: int('years, default 5, max 20') }, ['indicator', 'country']),
    async run(env, { indicator, country, n }) { const r = await httpJson(env, `https://api.worldbank.org/v2/country/${enc(String(country).toLowerCase())}/indicator/${enc(indicator)}?format=json&per_page=${capN(n, 5)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('world_bank', r); const rows = Array.isArray(r.json) ? (r.json[1] || []) : []; const named = rows.find(x => x.value != null); if (!rows.length) return `world_bank: no data for ${indicator} / ${country}.`; return `${(named && named.indicator && named.indicator.value) || indicator} — ${(named && named.country && named.country.value) || country}: ` + rows.filter(x => x.value != null).map(x => `${x.date}: ${Number(x.value).toLocaleString('en-US', { maximumFractionDigits: 2 })}`).join(' · '); } }
];
