// CATALOGUE — DEV & INFRA (asgard-upgrade Phase 7.6). Hulk; the SYSTEM routine.
// Read-only. Never anything that deploys, edits code, or touches secrets.
import { httpGet, httpJson, httpFetch, publicHostCheck, clip, capN, errorText, stripTags } from '../lib/http.js';
const S = (props, required = []) => ({ type: 'object', properties: props, required });
const str = d => ({ type: 'string', description: d }), int = d => ({ type: 'integer', description: d });
const enc = encodeURIComponent; const G = 'dev';
const ago = iso => { const s = (Date.now() - Date.parse(iso)) / 1000; return !isFinite(s) ? '' : s < 3600 ? `${Math.round(s / 60)} min ago` : s < 86400 ? `${Math.round(s / 3600)} h ago` : `${Math.round(s / 86400)} d ago`; };
async function sha(text, algo) { const buf = await crypto.subtle.digest(algo, new TextEncoder().encode(String(text))); return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join(''); }

export const TOOLS = [
  { name: 'cloudflare_status', group: G, taint: true, description: 'Cloudflare\'s own status page summary: overall indicator and any open incidents.', input_schema: S({}),
    async run(env) { const r = await httpJson(env, 'https://www.cloudflarestatus.com/api/v2/summary.json', { cacheSeconds: 120 }); if (!r.ok) return errorText('cloudflare_status', r); const j = r.json || {}; const inc = (j.incidents || []).slice(0, 5).map(i => `- ${i.name} (${i.status}, ${i.impact}) ${ago(i.updated_at)}`); return `Cloudflare: ${(j.status || {}).description || '?'}.${inc.length ? '\nOpen incidents:\n' + inc.join('\n') : ' No open incidents.'}`; } },
  { name: 'github_activity', group: G, taint: true, description: 'Recent public activity on a GitHub repo (owner/name): latest commits and open issues. No key — 60 requests/hour shared with everyone on this edge; may answer 403.', input_schema: S({ repo: str('owner/name, e.g. RAY09-F/rayven-pwa'), n: int('commits, default 5, max 20') }, ['repo']),
    async run(env, { repo, n }) { const rp = String(repo || '').replace(/^https?:\/\/github\.com\//, '').replace(/\/$/, ''); if (!/^[\w.-]+\/[\w.-]+$/.test(rp)) return 'github_activity: give the repo as owner/name.'; const h = { accept: 'application/vnd.github+json' }; const [c, i] = await Promise.all([httpJson(env, `https://api.github.com/repos/${rp}/commits?per_page=${capN(n, 5)}`, { headers: h, cacheSeconds: 300 }), httpJson(env, `https://api.github.com/repos/${rp}/issues?state=open&per_page=5`, { headers: h, cacheSeconds: 300 })]); if (!c.ok) return errorText('github_activity', c); const commits = (c.json || []).map(x => `- ${String(x.sha).slice(0, 7)} ${String((x.commit || {}).message || '').split('\n')[0].slice(0, 90)} — ${((x.commit || {}).author || {}).name || '?'}, ${ago(((x.commit || {}).author || {}).date)}`); const issues = i.ok ? (i.json || []).filter(x => !x.pull_request).map(x => `- #${x.number} ${x.title} (${ago(x.updated_at)})`) : []; return clip(`${rp} — latest commits:\n${commits.join('\n') || 'none'}${issues.length ? '\nOpen issues:\n' + issues.join('\n') : ''}`); } },
  { name: 'npm_info', group: G, taint: true, description: 'An npm package: latest version, description, license, last publish, weekly downloads.', input_schema: S({ pkg: str('package name') }, ['pkg']),
    async run(env, { pkg }) { const name = String(pkg || '').trim().toLowerCase(); const [r, d] = await Promise.all([httpJson(env, `https://registry.npmjs.org/${enc(name).replace('%40', '@')}`, { cacheSeconds: 3600, maxBytes: 1024 * 1024 }), httpJson(env, `https://api.npmjs.org/downloads/point/last-week/${enc(name).replace('%40', '@')}`, { cacheSeconds: 3600 })]); if (!r.ok) return errorText('npm_info', r); const j = r.json || {}; const latest = (j['dist-tags'] || {}).latest; const t = (j.time || {})[latest]; return `${j.name}@${latest} — ${String(j.description || '').slice(0, 160)}. License ${j.license || '?'}, published ${t ? ago(t) : '?'}${d.ok && d.json ? `, ${Number(d.json.downloads).toLocaleString('en-US')} downloads last week` : ''}. https://www.npmjs.com/package/${name}`; } },
  { name: 'pypi_info', group: G, taint: true, description: 'A PyPI package: latest version, summary, license, home page.', input_schema: S({ pkg: str('package name') }, ['pkg']),
    async run(env, { pkg }) { const r = await httpJson(env, `https://pypi.org/pypi/${enc(String(pkg).trim())}/json`, { cacheSeconds: 3600, maxBytes: 1024 * 1024 }); if (!r.ok) return errorText('pypi_info', r); const i = (r.json || {}).info || {}; return `${i.name} ${i.version} — ${String(i.summary || '').slice(0, 160)}. License ${String(i.license || '?').slice(0, 40)}. Requires ${i.requires_python || 'any Python'}. ${i.home_page || i.project_url || ''}`; } },
  { name: 'dns_lookup', group: G, taint: true, description: 'DNS records for a name via Cloudflare DNS over HTTPS: A, AAAA, MX, TXT, NS, CNAME.', input_schema: S({ name: str('host name'), type: { type: 'string', enum: ['A', 'AAAA', 'MX', 'TXT', 'NS', 'CNAME'] } }, ['name']),
    async run(env, { name, type }) { const r = await httpJson(env, `https://cloudflare-dns.com/dns-query?name=${enc(String(name).trim())}&type=${enc(type || 'A')}`, { headers: { accept: 'application/dns-json' }, cacheSeconds: 300 }); if (!r.ok) return errorText('dns_lookup', r); const a = (r.json || {}).Answer || []; if (!a.length) return `No ${type || 'A'} records for ${name} (status ${(r.json || {}).Status}).`; return a.map(x => `${x.name} ${x.type === 1 ? 'A' : x.type === 28 ? 'AAAA' : x.type === 15 ? 'MX' : x.type === 16 ? 'TXT' : x.type === 2 ? 'NS' : x.type === 5 ? 'CNAME' : x.type} ${x.data} (TTL ${x.TTL})`).join('\n'); } },
  { name: 'whois', group: G, taint: true, description: 'Domain registration facts via RDAP: registrar, created, expires, status, name servers.', input_schema: S({ domain: str('domain, e.g. example.com') }, ['domain']),
    async run(env, { domain }) { const d = String(domain || '').trim().toLowerCase().replace(/^https?:\/\//, '').split('/')[0]; const r = await httpJson(env, `https://rdap.org/domain/${enc(d)}`, { headers: { accept: 'application/rdap+json, application/json' }, cacheSeconds: 86400 }); if (!r.ok) return errorText('whois', r); const j = r.json || {}; const ev = k => ((j.events || []).find(e => e.eventAction === k) || {}).eventDate; const registrar = ((j.entities || []).find(e => (e.roles || []).includes('registrar')) || {}); const rn = ((registrar.vcardArray || [])[1] || []).find(x => x[0] === 'fn'); return `${j.ldhName || d}: registrar ${rn ? rn[3] : '?'}; registered ${(ev('registration') || '?').slice(0, 10)}; expires ${(ev('expiration') || '?').slice(0, 10)}; status ${(j.status || []).slice(0, 3).join(', ') || '?'}; name servers ${(j.nameservers || []).map(n => n.ldhName).slice(0, 4).join(', ') || '?'}.`; } },
  { name: 'http_check', group: G, taint: true, description: 'Check a URL: status code, server, content type, and the redirect chain (followed by hand, each hop guarded).', input_schema: S({ url: str('https URL') }, ['url']),
    async run(env, { url }) { const r = await httpFetch(env, url, { binary: true, accept: '*/*', maxBytes: 64 * 1024 }); if (!r.ok && r.status === 0) return errorText('http_check', r); return `${url} → HTTP ${r.status}${r.hops ? ` after ${r.hops} redirect(s), final ${r.url}` : ''}; content-type ${r.contentType || '?'}; ${r.bytes ? r.bytes.byteLength : 0} bytes read (capped).`; } },
  { name: 'url_shorten', group: G, taint: false, description: 'Shorten a public https URL with is.gd. Waits for approval when the session has read outside content.', input_schema: S({ url: str('the long URL') }, ['url']),
    async run(env, { url }) { const g = publicHostCheck(url); if (!g.ok) return `url_shorten: ${g.why}`; const r = await httpJson(env, `https://is.gd/create.php?format=json&url=${enc(url)}`); if (r.ok && r.json && r.json.shorturl) return `${r.json.shorturl} → ${url}`; const t = await httpGet(env, `https://tinyurl.com/api-create.php?url=${enc(url)}`, { accept: 'text/plain, */*' }); if (t.ok && /^https?:\/\/tinyurl\.com\//.test(t.text.trim())) return `${t.text.trim()} → ${url} (TinyURL; is.gd was unavailable)`; return `url_shorten: is.gd said ${r.error || (r.json && r.json.errormessage) || r.text.slice(0, 80)}; TinyURL said ${t.error || t.text.slice(0, 80)}`; } },
  { name: 'url_unshorten', group: G, taint: true, description: 'Where a short link really goes: follows redirects by hand (each hop checked) and reports the final URL.', input_schema: S({ url: str('the short URL') }, ['url']),
    async run(env, { url }) { const r = await httpFetch(env, url, { binary: true, accept: '*/*', maxBytes: 16 * 1024 }); if (!r.ok && r.status === 0) return errorText('url_unshorten', r); return r.hops ? `${url} → ${r.url} (${r.hops} hop${r.hops === 1 ? '' : 's'}, final status ${r.status})` : `${url} does not redirect (status ${r.status}).`; } },
  { name: 'qr_code', group: G, taint: false, description: 'A QR code image URL for some text or a link (api.qrserver.com). Waits for approval when the session has read outside content.', input_schema: S({ text: str('text or URL to encode'), size: int('pixels, default 240') }, ['text']),
    async run(env, { text, size }) { const s = Math.max(80, Math.min(1000, Number(size) || 240)); return `https://api.qrserver.com/v1/create-qr-code/?size=${s}x${s}&data=${enc(String(text).slice(0, 1000))}`; } },
  { name: 'page_preview', group: G, taint: true, description: 'Title, description and image of a public web page (Microlink, free tier).', input_schema: S({ url: str('https URL') }, ['url']),
    async run(env, { url }) { const r = await httpJson(env, `https://api.microlink.io/?url=${enc(url)}`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('page_preview', r); const d = (r.json || {}).data || {}; if ((r.json || {}).status !== 'success') return `page_preview: ${(r.json || {}).message || 'no preview'}`; return `${d.title || '(no title)'}${d.publisher ? ` — ${d.publisher}` : ''}\n${d.description || ''}${d.image && d.image.url ? `\nimage: ${d.image.url}` : ''}${d.date ? `\n${d.date}` : ''}`; } },
  { name: 'color_info', group: G, taint: true, description: 'A colour by hex (E7C24A) or name: its name, RGB, HSL, and a contrasting text colour (thecolorapi).', input_schema: S({ color: str('hex without # or a colour name') }, ['color']),
    async run(env, { color }) { const c = String(color || '').trim().replace(/^#/, ''); const q = /^[0-9a-f]{3,6}$/i.test(c) ? `hex=${c}` : `named=${enc(c)}`; const r = await httpJson(env, `https://www.thecolorapi.com/id?${q}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('color_info', r); const j = r.json || {}; return `${(j.name || {}).value || c}: ${(j.hex || {}).value} · ${(j.rgb || {}).value} · ${(j.hsl || {}).value} · text on it ${(j.contrast || {}).value}`; } },
  { name: 'text_hash', group: G, taint: false, description: 'Hash text locally: sha256 (default), sha1, sha384 or sha512.', input_schema: S({ text: str('the text'), algorithm: { type: 'string', enum: ['sha256', 'sha1', 'sha384', 'sha512'] } }, ['text']),
    async run(env, { text, algorithm }) { const a = { sha256: 'SHA-256', sha1: 'SHA-1', sha384: 'SHA-384', sha512: 'SHA-512' }[algorithm || 'sha256']; return `${algorithm || 'sha256'}: ${await sha(text, a)}`; } },
  { name: 'base64', group: G, taint: false, description: 'Base64-encode or decode text locally.', input_schema: S({ text: str('the text'), mode: { type: 'string', enum: ['encode', 'decode'] } }, ['text']),
    async run(env, { text, mode }) { try { if (mode === 'decode') return clip(new TextDecoder().decode(Uint8Array.from(atob(String(text).trim()), c => c.charCodeAt(0)))); return clip(btoa(String.fromCharCode(...new TextEncoder().encode(String(text))))); } catch (e) { return `base64: ${e.message}`; } } },
  { name: 'uuid', group: G, taint: false, description: 'Generate random UUIDs (up to 20).', input_schema: S({ n: int('how many, default 1, max 20') }),
    async run(env, { n }) { return Array.from({ length: capN(n, 1) }, () => crypto.randomUUID()).join('\n'); } },
  { name: 'regex_test', group: G, taint: false, description: 'Test a JavaScript regular expression against text: the matches (with groups), locally.', input_schema: S({ pattern: str('the pattern, without slashes'), flags: str('flags, e.g. gi'), text: str('the text') }, ['pattern', 'text']),
    async run(env, { pattern, flags, text }) { try { const re = new RegExp(pattern, (flags || 'g').replace(/[^gimsuy]/g, '')); const out = []; let m; if (re.global) { while ((m = re.exec(text)) && out.length < 20) { out.push(`"${m[0]}" at ${m.index}${m.length > 1 ? ` groups: ${m.slice(1).map(x => JSON.stringify(x)).join(', ')}` : ''}`); if (!m[0]) re.lastIndex++; } } else { m = re.exec(text); if (m) out.push(`"${m[0]}" at ${m.index}`); } return out.length ? `${out.length} match(es):\n${out.join('\n')}` : 'no match'; } catch (e) { return `regex_test: ${e.message}`; } } },
  { name: 'json_pretty', group: G, taint: false, description: 'Validate and pretty-print JSON locally (also summarises the top-level shape).', input_schema: S({ json: str('the JSON text') }, ['json']),
    async run(env, { json }) { try { const j = JSON.parse(String(json)); const shape = Array.isArray(j) ? `array of ${j.length}` : j && typeof j === 'object' ? `object with keys ${Object.keys(j).slice(0, 20).join(', ')}` : typeof j; return `Valid JSON (${shape}).\n${clip(JSON.stringify(j, null, 2), 5000)}`; } catch (e) { return `Not valid JSON: ${e.message}`; } } }
];
