// CATALOGUE — MARKETS & ECONOMY (asgard-upgrade Phase 7.2). Odin's court. All
// read-only; nothing here trades; PAPER / SIMULATED wherever a number touches
// the simulation. Per-IP-limited no-key sources are fallbacks, not pollers.
import { httpGet, httpJson, clip, capN, errorText } from '../lib/http.js';
import { readCappedLog } from '../lib/util.js';
const S = (props, required = []) => ({ type: 'object', properties: props, required });
const str = d => ({ type: 'string', description: d }), int = d => ({ type: 'integer', description: d }), num = d => ({ type: 'number', description: d });
const enc = encodeURIComponent; const G = 'markets';
const money = v => (typeof v === 'number' && isFinite(v) ? (Math.abs(v) >= 1 ? v.toLocaleString('en-US', { maximumFractionDigits: 2 }) : v.toPrecision(4)) : '—');
const pct = v => (typeof v === 'number' && isFinite(v) ? `${v >= 0 ? '+' : ''}${v.toFixed(2)}%` : '—');

export const TOOLS = [
  { name: 'coingecko_price', group: G, taint: true, description: 'Current USD price and 24h change for one or more coins by CoinGecko id (bitcoin, ethereum, solana …). No key; cached 60 s.', input_schema: S({ ids: str('comma-separated CoinGecko ids, e.g. bitcoin,ethereum') }, ['ids']),
    async run(env, { ids }) { const list = String(ids || '').toLowerCase().split(',').map(s => s.trim()).filter(Boolean).slice(0, 20); const r = await httpJson(env, `https://api.coingecko.com/api/v3/simple/price?ids=${enc(list.join(','))}&vs_currencies=usd&include_24hr_change=true&include_market_cap=true`, { cacheSeconds: 60 }); if (r.ok) { const out = Object.entries(r.json || {}).map(([id, v]) => `${id}: $${money(v.usd)} (${pct(v.usd_24h_change)} 24h, mcap $${money(v.usd_market_cap)})`); if (out.length) return out.join('\n'); }
      // CoinGecko's no-key tier is shared with every tenant on this edge address and is often exhausted: fall back to Coinbase spot prices (no 24h change).
      const SYM = { bitcoin: 'BTC', ethereum: 'ETH', solana: 'SOL', dogecoin: 'DOGE', cardano: 'ADA', ripple: 'XRP', litecoin: 'LTC', polkadot: 'DOT', chainlink: 'LINK', avalanche: 'AVAX', 'avalanche-2': 'AVAX', 'bitcoin-cash': 'BCH', uniswap: 'UNI', stellar: 'XLM', 'shiba-inu': 'SHIB', tether: 'USDT', 'usd-coin': 'USDC' };
      const outs = await Promise.all(list.map(async id => { const sym = SYM[id] || id.toUpperCase(); const c = await httpJson(env, `https://api.coinbase.com/v2/prices/${enc(sym)}-USD/spot`, { cacheSeconds: 60 }); return c.ok && c.json && c.json.data ? `${id}: $${money(Number(c.json.data.amount))} (Coinbase spot; CoinGecko was rate-limited)` : `${id}: no price (${c.error || 'unknown'})`; }));
      return outs.join('\n'); } },
  { name: 'coingecko_markets', group: G, taint: true, description: 'Top coins by market cap with price, 24h change and volume (n up to 20). No key; cached 60 s.', input_schema: S({ n: int('how many, default 10, max 20') }),
    async run(env, { n }) { const r = await httpJson(env, `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=${capN(n)}&page=1&sparkline=false`, { cacheSeconds: 60 }); if (r.ok && Array.isArray(r.json) && r.json.length) return clip(r.json.map((c, i) => `${i + 1}. ${c.name} (${String(c.symbol).toUpperCase()}) $${money(c.current_price)} ${pct(c.price_change_percentage_24h)} · mcap $${money(c.market_cap)} · vol $${money(c.total_volume)}`).join('\n'));
      const p = await httpJson(env, `https://api.coinpaprika.com/v1/tickers?quotes=USD&limit=${capN(n)}`, { cacheSeconds: 60, maxBytes: 1024 * 1024 }); if (!p.ok) return errorText('coingecko_markets', p); return clip((p.json || []).slice(0, capN(n)).map((c, i) => { const q = (c.quotes || {}).USD || {}; return `${i + 1}. ${c.name} (${c.symbol}) $${money(q.price)} ${pct(q.percent_change_24h)} · mcap $${money(q.market_cap)} · vol $${money(q.volume_24h)}`; }).join('\n') + '\n(Coinpaprika; CoinGecko was rate-limited)'); } },
  { name: 'coingecko_trending', group: G, taint: true, description: 'The coins trending on CoinGecko right now (searches in the last 24h).', input_schema: S({}),
    async run(env) { const r = await httpJson(env, 'https://api.coingecko.com/api/v3/search/trending', { cacheSeconds: 300 }); if (!r.ok) return errorText('coingecko_trending', r); return clip(((r.json || {}).coins || []).slice(0, 15).map((x, i) => { const c = x.item || {}; return `${i + 1}. ${c.name} (${c.symbol}) rank #${c.market_cap_rank || '?'}${c.data && c.data.price ? ` $${money(Number(c.data.price))}` : ''}`; }).join('\n')); } },
  { name: 'dexscreener_search', group: G, taint: true, description: 'Search DEX pairs on DexScreener by token name, symbol or address: chain, DEX, price, 24h change, liquidity.', input_schema: S({ q: str('token name, symbol or address'), n: int('pairs, default 8, max 20') }, ['q']),
    async run(env, { q, n }) { const r = await httpJson(env, `https://api.dexscreener.com/latest/dex/search?q=${enc(q)}`, { cacheSeconds: 60 }); if (!r.ok) return errorText('dexscreener_search', r); return clip(((r.json || {}).pairs || []).slice(0, capN(n, 8)).map((p, i) => `${i + 1}. ${p.baseToken.symbol}/${p.quoteToken.symbol} on ${p.chainId}/${p.dexId}: $${money(Number(p.priceUsd))} ${pct(p.priceChange && p.priceChange.h24)} · liq $${money(p.liquidity && p.liquidity.usd)} · ${p.url}`).join('\n') || 'no pairs'); } },
  { name: 'defillama_tvl', group: G, taint: true, description: 'Total value locked for one DeFi protocol (DefiLlama slug, e.g. aave, uniswap, lido) or one chain (e.g. Ethereum, Solana).', input_schema: S({ protocol: str('protocol slug'), chain: str('chain name, used when protocol is empty') }),
    async run(env, { protocol, chain }) { if (protocol) { const r = await httpGet(env, `https://api.llama.fi/tvl/${enc(String(protocol).toLowerCase())}`, { cacheSeconds: 600 }); if (!r.ok) return errorText('defillama_tvl', r); const v = Number(r.text); return isFinite(v) ? `${protocol}: TVL $${money(v)}` : `defillama_tvl: unexpected answer "${r.text.slice(0, 80)}"`; } if (chain) { const r = await httpJson(env, 'https://api.llama.fi/v2/chains', { cacheSeconds: 600 }); if (!r.ok) return errorText('defillama_tvl', r); const c = (r.json || []).find(x => String(x.name).toLowerCase() === String(chain).toLowerCase()); return c ? `${c.name}: TVL $${money(c.tvl)}` : `No chain called ${chain} on DefiLlama.`; } return 'defillama_tvl needs a protocol slug or a chain name (never the whole list — it is many megabytes).'; } },
  { name: 'btc_mempool', group: G, taint: true, description: 'Bitcoin network right now: recommended fees (sat/vB) and mempool size, from mempool.space.', input_schema: S({}),
    async run(env) { const [f, m] = await Promise.all([httpJson(env, 'https://mempool.space/api/v1/fees/recommended', { cacheSeconds: 60 }), httpJson(env, 'https://mempool.space/api/mempool', { cacheSeconds: 60 })]); if (!f.ok) return errorText('btc_mempool', f); const fe = f.json || {}, me = m.ok ? m.json || {} : {}; return `Fees (sat/vB): fastest ${fe.fastestFee}, ~30 min ${fe.halfHourFee}, ~1 h ${fe.hourFee}, economy ${fe.economyFee}, minimum ${fe.minimumFee}.${me.count ? ` Mempool: ${me.count.toLocaleString('en-US')} transactions, ${(me.vsize / 1e6).toFixed(1)} MvB.` : ''}`; } },
  { name: 'fear_greed', group: G, taint: true, description: 'The Crypto Fear & Greed index (alternative.me): today and the last 7 days.', input_schema: S({}),
    async run(env) { const r = await httpJson(env, 'https://api.alternative.me/fng/?limit=7', { cacheSeconds: 1800 }); if (!r.ok) return errorText('fear_greed', r); const d = (r.json || {}).data || []; if (!d.length) return 'fear_greed: no data'; return `Now: ${d[0].value} (${d[0].value_classification}). Last 7 days: ${d.map(x => x.value).join(', ')}.`; } },
  { name: 'stooq_quote', group: G, taint: true, description: 'Delayed / end-of-day quote for a stock or ETF from Stooq (free fallback when Twelve Data is out): open, high, low, close, volume. Symbol like SPY or AAPL.', input_schema: S({ symbol: str('ticker, e.g. SPY') }, ['symbol']),
    async run(env, { symbol }) { const s = String(symbol || '').trim().toLowerCase().replace(/[^a-z0-9.^-]/g, ''); let r = await httpGet(env, `https://stooq.com/q/l/?s=${enc(s.includes('.') ? s : s + '.us')}&f=sd2t2ohlcv&h&e=csv`, { accept: 'text/csv, */*', cacheSeconds: 300 }); if (!r.ok || !/^Symbol/i.test(r.text.trim())) r = await httpGet(env, `https://stooq.pl/q/l/?s=${enc(s.includes('.') ? s : s + '.us')}&f=sd2t2ohlcv&h&e=csv`, { accept: 'text/csv, */*', cacheSeconds: 300 }); if (!r.ok) return errorText('stooq_quote', r); const lines = r.text.trim().split('\n'); if (lines.length < 2) return `stooq_quote: no data for ${symbol}`; const h = lines[0].split(','), v = lines[1].split(','); const o = Object.fromEntries(h.map((k, i) => [k, v[i]])); if (o.Close === 'N/D' || !o.Close) return `Stooq has no quote for ${symbol}.`; return `${String(symbol).toUpperCase()} (delayed, ${o.Date} ${o.Time}): open ${o.Open}, high ${o.High}, low ${o.Low}, close ${o.Close}, volume ${o.Volume}.`; } },
  { name: 'treasury_yields', group: G, taint: true, description: 'The latest US Treasury par yield curve (1-month to 30-year) from the Treasury\'s own daily XML feed.', input_schema: S({}),
    async run(env) { const d = new Date(); const ym = `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}`; let r = await httpGet(env, `https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value_month=${ym}`, { accept: 'application/xml, text/xml, */*', cacheSeconds: 3600, timeoutMs: 18000 }); if (!r.ok) return errorText('treasury_yields', r); const entries = r.text.split(/<entry>/i).slice(1); if (!entries.length) return 'treasury_yields: the feed had no entries yet this month.'; const last = entries[entries.length - 1]; const g = k => { const m = new RegExp(`<d:${k}[^>]*>([^<]*)<`, 'i').exec(last); return m ? m[1] : null; }; const date = (g('NEW_DATE') || '').slice(0, 10); const rows = [['1 mo', 'BC_1MONTH'], ['3 mo', 'BC_3MONTH'], ['6 mo', 'BC_6MONTH'], ['1 yr', 'BC_1YEAR'], ['2 yr', 'BC_2YEAR'], ['5 yr', 'BC_5YEAR'], ['10 yr', 'BC_10YEAR'], ['30 yr', 'BC_30YEAR']].map(([l, k]) => `${l} ${g(k) || '—'}%`); return `US Treasury par yields, ${date}: ${rows.join(' · ')}.`; } },
  { name: 'bls_latest', group: G, taint: true, description: 'Latest values of a BLS series (no key, 25/day), e.g. LNS14000000 unemployment rate, CUUR0000SA0 CPI-U. May refuse cloud addresses.', input_schema: S({ series: str('BLS series id') }, ['series']),
    async run(env, { series }) { const r = await httpJson(env, `https://api.bls.gov/publicAPI/v1/timeseries/data/${enc(String(series).toUpperCase())}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('bls_latest', r); const s = ((((r.json || {}).Results || {}).series || [])[0] || {}); const d = (s.data || []).slice(0, 6); if (!d.length) return `bls_latest: ${(r.json && r.json.message || []).join('; ') || 'no data'}`; return `${series}: ${d.map(x => `${x.periodName} ${x.year} = ${x.value}`).join(' · ')}`; } },
  { name: 'polymarket_markets', group: G, taint: true, description: 'READ-ONLY: active Polymarket prediction markets matching a query, with the current yes-price. No wallet, no trading, ever.', input_schema: S({ q: str('words in the market title'), n: int('markets, default 8, max 20') }, ['q']),
    async run(env, { q, n }) { const r = await httpJson(env, 'https://gamma-api.polymarket.com/markets?active=true&closed=false&limit=100&order=volume24hr&ascending=false', { cacheSeconds: 300 }); if (!r.ok) return errorText('polymarket_markets', r); const words = String(q || '').toLowerCase().split(/\s+/).filter(Boolean); const hits = (r.json || []).filter(m => words.every(w => String(m.question || '').toLowerCase().includes(w))).slice(0, capN(n, 8)); return clip(hits.map((m, i) => { let yes = null; try { yes = JSON.parse(m.outcomePrices || '[]')[0]; } catch (e) {} return `${i + 1}. ${m.question} — yes ${yes != null ? Math.round(Number(yes) * 100) + '%' : '?'}, 24h vol $${money(Number(m.volume24hr) || 0)} (read-only)`; }).join('\n') || `No active markets mention "${q}".`); } },
  { name: 'fx_rates', group: G, taint: true, description: 'Exchange rates for a base currency (open.er-api.com; the fallback when Frankfurter fails): the majors, or a specific target.', input_schema: S({ base: str('3-letter code, default USD'), to: str('optional target code') }),
    async run(env, { base, to }) { const b = String(base || 'USD').toUpperCase().slice(0, 3); const r = await httpJson(env, `https://open.er-api.com/v6/latest/${enc(b)}`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('fx_rates', r); const rates = (r.json || {}).rates || {}; if (to) { const t = String(to).toUpperCase().slice(0, 3); return rates[t] ? `1 ${b} = ${rates[t]} ${t} (${(r.json || {}).time_last_update_utc || ''})` : `No rate for ${t}.`; } return `1 ${b} = ${['EUR', 'GBP', 'JPY', 'CAD', 'MXN', 'CHF', 'AUD', 'CNY', 'INR'].filter(k => rates[k]).map(k => `${rates[k]} ${k}`).join(' · ')} (${(r.json || {}).time_last_update_utc || ''})`; } },
  { name: 'paper_equity_chart', group: 'paper', taint: false, description: 'A PNG chart URL (QuickChart) of the PAPER book\'s simulated cash over time, built from the recorded equity curve. The spec is built by code, never by the model. PAPER / SIMULATED.', input_schema: S({}),
    async run(env) { const eq = await readCappedLog(env, 'paper:equity'); if (!eq.length) return 'PAPER equity chart: no equity points recorded yet.'; const pts = eq.slice(-120); const labels = pts.map(p => new Date(p.time).toISOString().slice(5, 10)); const data = pts.map(p => Math.round(p.cash * 100) / 100); const spec = { type: 'line', data: { labels, datasets: [{ label: 'PAPER cash (simulated)', data, borderColor: '#D8AE5A', backgroundColor: 'rgba(216,174,90,0.15)', fill: true, pointRadius: 0 }] }, options: { plugins: { title: { display: true, text: 'PAPER / SIMULATED — no real money' } }, scales: { x: { ticks: { maxTicksLimit: 8 } } } } }; return `PAPER / SIMULATED equity curve (${pts.length} points, cash only): https://quickchart.io/chart?w=720&h=360&bkg=%230B0A12&c=${enc(JSON.stringify(spec))}`; } }
];
