// CATALOGUE — LIFE ADMIN (asgard-upgrade Phase 7.4). Miss Minutes, Mobius, Darcy.
// All state in ONE KV key per tool family (life:shopping, life:notes, life:reading,
// life:habits, life:expenses), written only on change. Rayan's own typed numbers
// only -- no bank data, no bank links.
import { httpJson, clip, capN, errorText } from '../lib/http.js';
const S = (props, required = []) => ({ type: 'object', properties: props, required });
const str = d => ({ type: 'string', description: d }), int = d => ({ type: 'integer', description: d }), num = d => ({ type: 'number', description: d });
const enc = encodeURIComponent; const G = 'life';
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Los_Angeles', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
async function readKey(env, k, d) { try { const raw = await env.RAYVEN_KV.get(k); return raw ? JSON.parse(raw) : d; } catch (e) { return d; } }
async function writeKey(env, k, v) { await env.RAYVEN_KV.put(k, JSON.stringify(v)); }
const norm = s => String(s || '').trim().toLowerCase();

// local unit conversion: length, weight, temperature, volume, speed, data
const UNITS = {
  length: { m: 1, km: 1000, cm: 0.01, mm: 0.001, mi: 1609.344, mile: 1609.344, miles: 1609.344, ft: 0.3048, feet: 0.3048, foot: 0.3048, in: 0.0254, inch: 0.0254, inches: 0.0254, yd: 0.9144, yard: 0.9144, yards: 0.9144, nmi: 1852 },
  weight: { kg: 1, g: 0.001, mg: 0.000001, lb: 0.45359237, lbs: 0.45359237, pound: 0.45359237, pounds: 0.45359237, oz: 0.028349523, ounce: 0.028349523, ounces: 0.028349523, st: 6.35029318, ton: 907.18474, tonne: 1000 },
  volume: { l: 1, liter: 1, litre: 1, liters: 1, ml: 0.001, gal: 3.785411784, gallon: 3.785411784, gallons: 3.785411784, qt: 0.946352946, quart: 0.946352946, pt: 0.473176473, pint: 0.473176473, cup: 0.2365882365, cups: 0.2365882365, floz: 0.0295735296, tbsp: 0.0147867648, tsp: 0.00492892159 },
  speed: { 'm/s': 1, kmh: 0.277778, 'km/h': 0.277778, kph: 0.277778, mph: 0.44704, knot: 0.514444, knots: 0.514444, kn: 0.514444 },
  data: { b: 1, byte: 1, bytes: 1, kb: 1e3, mb: 1e6, gb: 1e9, tb: 1e12, kib: 1024, mib: 1048576, gib: 1073741824, tib: 1099511627776, bit: 0.125, kbit: 125, mbit: 125000, gbit: 125000000 }
};
function convertUnits(value, from, to) {
  const v = Number(value), f = norm(from).replace(/\s+/g, ''), t = norm(to).replace(/\s+/g, '');
  if (!isFinite(v)) return 'unit_convert: the value must be a number.';
  const temp = { c: 'c', celsius: 'c', f: 'f', fahrenheit: 'f', k: 'k', kelvin: 'k' };
  if (temp[f] && temp[t]) { let c = temp[f] === 'c' ? v : temp[f] === 'f' ? (v - 32) * 5 / 9 : v - 273.15; const out = temp[t] === 'c' ? c : temp[t] === 'f' ? c * 9 / 5 + 32 : c + 273.15; return `${v} °${temp[f].toUpperCase()} = ${Math.round(out * 100) / 100} °${temp[t].toUpperCase()}`; }
  for (const [fam, table] of Object.entries(UNITS)) if (table[f] != null && table[t] != null) { const out = v * table[f] / table[t]; return `${v} ${from} = ${out >= 1000 ? out.toLocaleString('en-US', { maximumFractionDigits: 2 }) : Number(out.toPrecision(6))} ${to} (${fam})`; }
  return `unit_convert: I can't convert ${from} to ${to}. Families: length, weight, temperature, volume, speed, data.`;
}

export const TOOLS = [
  { name: 'shopping_list', group: G, taint: false, description: 'Rayan\'s shopping list: action add / remove / read / clear, with an item name.', input_schema: S({ action: { type: 'string', enum: ['add', 'remove', 'read', 'clear'] }, item: str('the item (for add / remove)') }, ['action']),
    async run(env, { action, item }) { const key = 'life:shopping'; const list = await readKey(env, key, []); if (action === 'read') return list.length ? `Shopping list (${list.length}): ${list.map(x => x.item).join(', ')}` : 'The shopping list is empty.'; if (action === 'clear') { if (list.length) await writeKey(env, key, []); return 'Shopping list cleared.'; } const it = String(item || '').trim(); if (!it) return 'Which item?'; if (action === 'add') { if (list.some(x => norm(x.item) === norm(it))) return `${it} is already on the list.`; list.push({ item: it, at: today() }); await writeKey(env, key, list.slice(-100)); return `Added ${it}. ${list.length} item${list.length === 1 ? '' : 's'} on the list.`; } const next = list.filter(x => norm(x.item) !== norm(it)); if (next.length === list.length) return `${it} wasn't on the list.`; await writeKey(env, key, next); return `Removed ${it}. ${next.length} left.`; } },
  { name: 'quick_note', group: G, taint: false, description: 'Jot a quick dated note (kept, never edited). Read them back with notes_read.', input_schema: S({ text: str('the note') }, ['text']),
    async run(env, { text }) { const t = String(text || '').trim().slice(0, 800); if (!t) return 'What should the note say?'; const key = 'life:notes'; const list = await readKey(env, key, []); list.push({ date: today(), at: new Date().toISOString(), text: t }); await writeKey(env, key, list.slice(-300)); return `Noted (${today()}). ${list.length} notes kept.`; } },
  { name: 'notes_read', group: G, taint: false, description: 'Read quick notes: for one date (YYYY-MM-DD) or the most recent ones.', input_schema: S({ date: str('YYYY-MM-DD, optional'), n: int('how many recent, default 10, max 20') }),
    async run(env, { date, n }) { const list = await readKey(env, 'life:notes', []); const sel = date ? list.filter(x => x.date === date) : list.slice(-capN(n)); return sel.length ? sel.map(x => `[${x.date} ${x.at.slice(11, 16)}Z] ${x.text}`).join('\n') : (date ? `No notes on ${date}.` : 'No notes yet.'); } },
  { name: 'reading_list', group: G, taint: false, description: 'Rayan\'s reading list (links or titles): action add / done / read.', input_schema: S({ action: { type: 'string', enum: ['add', 'done', 'read'] }, item: str('a URL or title (for add / done)') }, ['action']),
    async run(env, { action, item }) { const key = 'life:reading'; const list = await readKey(env, key, []); if (action === 'read') { const open = list.filter(x => !x.done); return open.length ? `Reading list (${open.length}):\n` + open.map((x, i) => `${i + 1}. ${x.item} (added ${x.at})`).join('\n') : 'The reading list is empty.'; } const it = String(item || '').trim(); if (!it) return 'Which item?'; if (action === 'add') { list.push({ item: it, at: today(), done: false }); await writeKey(env, key, list.slice(-200)); return `Added to the reading list (${list.filter(x => !x.done).length} open).`; } const hit = list.find(x => !x.done && norm(x.item).includes(norm(it))); if (!hit) return `Nothing open matches "${it}".`; hit.done = true; hit.doneAt = today(); await writeKey(env, key, list); return `Marked done: ${hit.item}.`; } },
  { name: 'habit_log', group: G, taint: false, description: 'Log a habit as done today (e.g. gym, water, reading). Streaks are counted from consecutive days.', input_schema: S({ name: str('habit name') }, ['name']),
    async run(env, { name }) { const h = norm(name); if (!h) return 'Which habit?'; const key = 'life:habits'; const all = await readKey(env, key, {}); const days = all[h] || []; const d = today(); if (days.includes(d)) return `${name} is already logged for today.`; days.push(d); all[h] = days.slice(-400); await writeKey(env, key, all); return `${name} logged for ${d}. Streak: ${streak(all[h])} day${streak(all[h]) === 1 ? '' : 's'}.`; } },
  { name: 'habits_status', group: G, taint: false, description: 'Every habit with its current streak and whether it is logged today.', input_schema: S({}),
    async run(env) { const all = await readKey(env, 'life:habits', {}); const names = Object.keys(all); if (!names.length) return 'No habits logged yet. Say "log gym" or "log water" to start one.'; const d = today(); return names.map(h => `${h}: streak ${streak(all[h])}, ${all[h].includes(d) ? 'done today' : 'NOT yet today'}, ${all[h].length} total`).join('\n'); } },
  { name: 'expense_log', group: G, taint: false, description: 'Log an expense Rayan tells you (amount in dollars, category, note). His own typed numbers only — no bank data.', input_schema: S({ amount: num('dollars'), category: str('category, e.g. food, gas, fun'), note: str('optional note') }, ['amount', 'category']),
    async run(env, { amount, category, note }) { const a = Number(amount); if (!isFinite(a) || a <= 0) return 'The amount must be a positive number of dollars.'; const key = 'life:expenses'; const list = await readKey(env, key, []); list.push({ date: today(), amount: Math.round(a * 100) / 100, category: norm(category) || 'other', note: String(note || '').slice(0, 120) }); await writeKey(env, key, list.slice(-1000)); return `Logged $${a.toFixed(2)} for ${category}${note ? ` (${note})` : ''}.`; } },
  { name: 'expenses_week', group: G, taint: false, description: 'This week\'s logged expenses: total and by category, plus the last few entries.', input_schema: S({ days: int('look back this many days, default 7, max 20') }),
    async run(env, { days }) { const list = await readKey(env, 'life:expenses', []); const since = new Date(Date.now() - capN(days, 7) * 86400000).toISOString().slice(0, 10); const w = list.filter(x => x.date >= since); if (!w.length) return `No expenses logged in the last ${capN(days, 7)} days.`; const by = {}; for (const x of w) by[x.category] = (by[x.category] || 0) + x.amount; const total = w.reduce((s, x) => s + x.amount, 0); return `Last ${capN(days, 7)} days: $${total.toFixed(2)} over ${w.length} entries. By category: ${Object.entries(by).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} $${v.toFixed(2)}`).join(', ')}. Latest: ${w.slice(-5).reverse().map(x => `${x.date} $${x.amount} ${x.category}${x.note ? ' — ' + x.note : ''}`).join(' | ')}`; } },
  { name: 'unit_convert', group: G, taint: false, description: 'Convert units locally: length, weight, temperature, volume, speed, data (e.g. 10 mi to km, 72 F to C, 3 cups to ml).', input_schema: S({ value: num('the number'), from: str('unit from'), to: str('unit to') }, ['value', 'from', 'to']),
    async run(env, { value, from, to }) { return convertUnits(value, from, to); } },
  { name: 'recipe_search', group: G, taint: true, description: 'Recipes from TheMealDB by name or main ingredient: name, category, area, link.', input_schema: S({ q: str('dish name or ingredient'), n: int('results, default 5, max 20') }, ['q']),
    async run(env, { q, n }) { let r = await httpJson(env, `https://www.themealdb.com/api/json/v1/1/search.php?s=${enc(q)}`, { cacheSeconds: 86400 }); if (r.ok && !(r.json && r.json.meals)) r = await httpJson(env, `https://www.themealdb.com/api/json/v1/1/filter.php?i=${enc(q)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('recipe_search', r); const meals = (r.json || {}).meals || []; if (!meals.length) return `No recipes for ${q}.`; return clip(meals.slice(0, capN(n, 5)).map((m, i) => `${i + 1}. ${m.strMeal}${m.strCategory ? ` — ${m.strCategory}, ${m.strArea}` : ''}${m.strSource ? `\n   ${m.strSource}` : ''} https://www.themealdb.com/meal/${m.idMeal}`).join('\n')); } },
  { name: 'cocktail_search', group: G, taint: true, description: 'Cocktail recipes from TheCocktailDB by name: ingredients and instructions.', input_schema: S({ q: str('cocktail name') }, ['q']),
    async run(env, { q }) { const r = await httpJson(env, `https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${enc(q)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('cocktail_search', r); const d = ((r.json || {}).drinks || [])[0]; if (!d) return `No cocktail called ${q}.`; const ings = []; for (let i = 1; i <= 15; i++) if (d[`strIngredient${i}`]) ings.push(`${d[`strMeasure${i}`] || ''} ${d[`strIngredient${i}`]}`.trim()); return `${d.strDrink} (${d.strAlcoholic}, ${d.strGlass}): ${ings.join(', ')}. ${String(d.strInstructions || '').slice(0, 400)}`; } },
  { name: 'food_by_barcode', group: G, taint: true, description: 'A packaged food by barcode (Open Food Facts): name, brand, Nutri-Score, calories and macros per 100 g.', input_schema: S({ code: str('barcode digits') }, ['code']),
    async run(env, { code }) { const r = await httpJson(env, `https://world.openfoodfacts.org/api/v2/product/${enc(String(code).replace(/\D/g, ''))}.json?fields=product_name,brands,nutriscore_grade,nutriments,quantity`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('food_by_barcode', r); const p = (r.json || {}).product; if (!p) return `No product for barcode ${code}.`; const nu = p.nutriments || {}; return `${p.product_name || '(unnamed)'}${p.brands ? ` — ${p.brands}` : ''}${p.quantity ? `, ${p.quantity}` : ''}. Nutri-Score ${(p.nutriscore_grade || '?').toUpperCase()}. Per 100 g: ${nu['energy-kcal_100g'] != null ? nu['energy-kcal_100g'] + ' kcal' : '? kcal'}, fat ${nu.fat_100g ?? '?'} g, carbs ${nu.carbohydrates_100g ?? '?'} g (sugars ${nu.sugars_100g ?? '?'} g), protein ${nu.proteins_100g ?? '?'} g, salt ${nu.salt_100g ?? '?'} g.`; } },
  { name: 'exercises', group: G, taint: true, description: 'Exercises for a muscle group from wger (biceps, triceps, chest, shoulders, back, abs, quads, hamstrings, glutes, calves): name and a short description.', input_schema: S({ muscle: str('muscle group'), n: int('results, default 5, max 20') }, ['muscle']),
    async run(env, { muscle, n }) { const MAP = { biceps: 1, shoulders: 2, chest: 4, triceps: 5, abs: 6, calves: 7, glutes: 8, traps: 9, quads: 10, hamstrings: 11, lats: 12, back: 12 }; const id = MAP[norm(muscle)]; if (!id) return `exercises: pick one of ${Object.keys(MAP).join(', ')}.`; const r = await httpJson(env, `https://wger.de/api/v2/exerciseinfo/?muscles=${id}&language=2&limit=${capN(n, 5)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('exercises', r); const list = (r.json || {}).results || []; return clip(list.map((e, i) => { const t = (e.translations || []).find(x => x.language === 2) || (e.translations || [])[0] || {}; return `${i + 1}. ${t.name || 'exercise ' + e.id}${e.equipment && e.equipment.length ? ` (${e.equipment.map(q => q.name).join(', ')})` : ''} — ${String(t.description || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 160)}`; }).join('\n') || `No exercises listed for ${muscle}.`); } },
  { name: 'vin_decode', group: G, taint: true, description: 'Decode a vehicle VIN (NHTSA): year, make, model, body, engine, plant.', input_schema: S({ vin: str('17-character VIN') }, ['vin']),
    async run(env, { vin }) { const r = await httpJson(env, `https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/${enc(String(vin).trim())}?format=json`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('vin_decode', r); const v = (((r.json || {}).Results || [])[0]) || {}; if (v.ErrorCode && !/^0\b/.test(String(v.ErrorCode)) && !v.Make) return `vin_decode: ${v.ErrorText || 'not a valid VIN'}`; return `${v.ModelYear} ${v.Make} ${v.Model}${v.Trim ? ` ${v.Trim}` : ''} — ${v.BodyClass || ''}, ${v.EngineCylinders ? v.EngineCylinders + ' cyl' : ''} ${v.DisplacementL ? v.DisplacementL + ' L' : ''} ${v.FuelTypePrimary || ''}, built in ${v.PlantCity || '?'}, ${v.PlantCountry || '?'}.`.replace(/\s+/g, ' '); } },
  { name: 'recalls', group: G, taint: true, description: 'US safety recalls for a vehicle (NHTSA): make, model, year → campaign, component, summary.', input_schema: S({ make: str('make'), model: str('model'), year: int('model year'), n: int('recalls, default 5, max 20') }, ['make', 'model', 'year']),
    async run(env, { make, model, year, n }) { const r = await httpJson(env, `https://api.nhtsa.gov/recalls/recallsByVehicle?make=${enc(make)}&model=${enc(model)}&modelYear=${enc(String(year))}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('recalls', r); const res = (r.json || {}).results || []; if (!res.length) return `No recalls on file for ${year} ${make} ${model}.`; return clip(`${res.length} recall(s) for ${year} ${make} ${model}:\n` + res.slice(0, capN(n, 5)).map((x, i) => `${i + 1}. ${x.NHTSACampaignNumber} (${x.ReportReceivedDate}) ${x.Component}: ${String(x.Summary || '').slice(0, 200)}`).join('\n')); } }
];
function streak(days) { const set = new Set(days); let n = 0; const d = new Date(); for (;;) { const s = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Los_Angeles', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d); if (!set.has(s)) { if (n === 0) { d.setDate(d.getDate() - 1); const y = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Los_Angeles', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d); if (!set.has(y)) return 0; continue; } return n; } n++; d.setDate(d.getDate() - 1); if (n > 400) return n; } }
