// CATALOGUE — MEDIA & ENTERTAINMENT (7.7) and CURIOSITIES (7.8). Valkyrie; Thor keeps the shelf.
// All free, all no-key, all harmless. Nothing that insults, profiles people by name, or quotes living people.
import { httpGet, httpJson, httpFetch, clip, capN, errorText, stripTags } from '../lib/http.js';
const S = (props, required = []) => ({ type: 'object', properties: props, required });
const str = d => ({ type: 'string', description: d }), int = d => ({ type: 'integer', description: d });
const enc = encodeURIComponent; const M = 'media', F = 'fun';

export const TOOLS = [
  // ---- media
  { name: 'itunes_search', group: M, taint: true, description: 'Search the iTunes / Apple catalogue: music, podcasts, apps, movies, ebooks (media: music | podcast | software | movie | ebook | all).', input_schema: S({ term: str('search terms'), media: { type: 'string', enum: ['music', 'podcast', 'software', 'movie', 'ebook', 'all'] }, n: int('results, default 5, max 20') }, ['term']),
    async run(env, { term, media, n }) { const r = await httpJson(env, `https://itunes.apple.com/search?term=${enc(term)}&media=${enc(media || 'all')}&limit=${capN(n, 5)}&country=US`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('itunes_search', r); return clip(((r.json || {}).results || []).map((x, i) => `${i + 1}. ${x.trackName || x.collectionName || x.artistName} — ${x.artistName || ''} (${x.kind || x.wrapperType}${x.releaseDate ? ', ' + String(x.releaseDate).slice(0, 4) : ''}) ${x.trackViewUrl || x.collectionViewUrl || ''}`).join('\n') || 'no results'); } },
  { name: 'tv_search', group: M, taint: true, description: 'A TV show on TVmaze: status, network, genres, premiere, summary, next episode.', input_schema: S({ show: str('show name') }, ['show']),
    async run(env, { show }) { const r = await httpJson(env, `https://api.tvmaze.com/singlesearch/shows?q=${enc(show)}&embed=nextepisode`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('tv_search', r); const s = r.json || {}; const ne = (s._embedded || {}).nextepisode; return `${s.name} (${s.premiered ? s.premiered.slice(0, 4) : '?'}, ${s.status}${s.network ? `, ${s.network.name}` : s.webChannel ? `, ${s.webChannel.name}` : ''}) — ${(s.genres || []).join(', ')}. ${stripTags(s.summary || '').slice(0, 300)}${ne ? ` Next: S${ne.season}E${ne.number} "${ne.name}" on ${ne.airdate}.` : ''} ${s.url || ''}`; } },
  { name: 'tv_tonight', group: M, taint: true, description: 'What airs tonight on TV in a country (TVmaze schedule; country like US, GB).', input_schema: S({ country: str('two-letter code, default US'), n: int('shows, default 10, max 20') }),
    async run(env, { country, n }) { const d = new Date().toISOString().slice(0, 10); const r = await httpJson(env, `https://api.tvmaze.com/schedule?country=${enc((country || 'US').toUpperCase().slice(0, 2))}&date=${d}`, { cacheSeconds: 3600, maxBytes: 1024 * 1024 }); if (!r.ok) return errorText('tv_tonight', r); const list = (r.json || []).filter(e => e.airtime >= '19:00').slice(0, capN(n)); return clip(list.map(e => `${e.airtime} ${(e.show || {}).name} — S${e.season}E${e.number}${e.name ? ` "${e.name}"` : ''}${(e.show || {}).network ? ` (${e.show.network.name})` : ''}`).join('\n') || 'nothing listed'); } },
  { name: 'anime_search', group: M, taint: true, description: 'Search anime on Jikan (MyAnimeList): title, type, episodes, score, year, synopsis snippet.', input_schema: S({ q: str('title'), n: int('results, default 5, max 20') }, ['q']),
    async run(env, { q, n }) { const r = await httpJson(env, `https://api.jikan.moe/v4/anime?q=${enc(q)}&limit=${capN(n, 5)}&sfw=true`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('anime_search', r); return clip(((r.json || {}).data || []).map((a, i) => `${i + 1}. ${a.title} (${a.type}, ${a.episodes || '?'} eps, ${a.year || '?'}, score ${a.score || '?'}) — ${String(a.synopsis || '').slice(0, 160)} ${a.url}`).join('\n') || 'no results'); } },
  { name: 'musicbrainz', group: M, taint: true, description: 'An artist on MusicBrainz: type, country, active years, tags.', input_schema: S({ artist: str('artist name') }, ['artist']),
    async run(env, { artist }) { const r = await httpJson(env, `https://musicbrainz.org/ws/2/artist/?query=${enc(artist)}&fmt=json&limit=3`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('musicbrainz', r); const a = ((r.json || {}).artists || [])[0]; if (!a) return `No artist called ${artist}.`; return `${a.name} (${a.type || '?'}${a.country ? `, ${a.country}` : ''}${a['life-span'] ? `, ${a['life-span'].begin || '?'}–${a['life-span'].end || 'present'}` : ''})${a.disambiguation ? ` — ${a.disambiguation}` : ''}. Tags: ${(a.tags || []).slice(0, 6).map(t => t.name).join(', ') || 'none'}. https://musicbrainz.org/artist/${a.id}`; } },
  { name: 'songlink', group: M, taint: true, description: 'Cross-platform links for a song or album (song.link / Odesli): give a Spotify, Apple Music or YouTube link, get the others.', input_schema: S({ url: str('a music link') }, ['url']),
    async run(env, { url }) { const r = await httpJson(env, `https://api.song.link/v1-alpha.1/links?url=${enc(url)}&userCountry=US`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('songlink', r); const j = r.json || {}; const ent = Object.values(j.entitiesByUniqueId || {})[0] || {}; return `${ent.title || ''}${ent.artistName ? ` — ${ent.artistName}` : ''}\n${Object.entries(j.linksByPlatform || {}).slice(0, 10).map(([p, l]) => `${p}: ${l.url}`).join('\n')}\nall: ${j.pageUrl || ''}`; } },
  { name: 'game_deals', group: M, taint: true, description: 'PC game deals from CheapShark: title, sale price, normal price, store link.', input_schema: S({ q: str('game title (optional; empty = today\'s best deals)'), n: int('deals, default 8, max 20') }),
    async run(env, { q, n }) { const r = await httpJson(env, `https://www.cheapshark.com/api/1.0/deals?${q ? `title=${enc(q)}&` : 'sortBy=DealRating&'}pageSize=${capN(n, 8)}`, { cacheSeconds: 3600 }); if (!r.ok) return errorText('game_deals', r); return clip((r.json || []).map((d, i) => `${i + 1}. ${d.title}: $${d.salePrice} (was $${d.normalPrice}, -${Math.round(Number(d.savings))}%) https://www.cheapshark.com/redirect?dealID=${d.dealID}`).join('\n') || 'no deals'); } },
  { name: 'free_games', group: M, taint: true, description: 'Games that are free right now: GamerPower giveaways plus a few free-to-play picks.', input_schema: S({ n: int('items, default 8, max 20') }),
    async run(env, { n }) { const [g, f] = await Promise.all([httpJson(env, 'https://www.gamerpower.com/api/giveaways?sort-by=date', { cacheSeconds: 3600 }), httpJson(env, 'https://www.freetogame.com/api/games?sort-by=popularity', { cacheSeconds: 86400, maxBytes: 1024 * 1024 })]); const k = capN(n, 8); const a = g.ok ? (g.json || []).slice(0, k).map(x => `- ${x.title} (${x.platforms}, ends ${x.end_date}) ${x.open_giveaway_url}`) : [`giveaways: ${g.error}`]; const b = f.ok ? (f.json || []).slice(0, 3).map(x => `- ${x.title} (${x.genre}, ${x.platform}) ${x.game_url}`) : []; return clip(`Giveaways now:\n${a.join('\n')}${b.length ? '\nPopular free-to-play:\n' + b.join('\n') : ''}`); } },
  { name: 'board_games', group: M, taint: true, description: 'Search BoardGameGeek for a board game: name, year, and the BGG link.', input_schema: S({ q: str('game name'), n: int('results, default 5, max 20') }, ['q']),
    async run(env, { q, n }) { const r = await httpGet(env, `https://boardgamegeek.com/xmlapi2/search?query=${enc(q)}&type=boardgame`, { accept: 'application/xml, text/xml, */*', cacheSeconds: 86400 }); if (!r.ok) return errorText('board_games', r); const items = [...r.text.matchAll(/<item[^>]*id="(\d+)"[^>]*>[\s\S]*?<name[^>]*value="([^"]*)"[\s\S]*?(?:<yearpublished[^>]*value="(\d+)")?[\s\S]*?<\/item>/g)].slice(0, capN(n, 5)); return items.length ? items.map((m, i) => `${i + 1}. ${m[2]}${m[3] ? ` (${m[3]})` : ''} https://boardgamegeek.com/boardgame/${m[1]}`).join('\n') : `No board game called ${q}.`; } },
  { name: 'trivia', group: F, taint: true, description: 'Trivia questions from Open Trivia DB (with answers), optional category id.', input_schema: S({ n: int('questions, default 3, max 20'), category: int('OpenTDB category id, optional') }),
    async run(env, { n, category }) { const r = await httpJson(env, `https://opentdb.com/api.php?amount=${capN(n, 3)}${category ? `&category=${Number(category)}` : ''}&type=multiple`); if (!r.ok) return errorText('trivia', r); const dec = s => stripTags(String(s).replace(/&quot;/g, '"').replace(/&#039;/g, "'").replace(/&amp;/g, '&')); return ((r.json || {}).results || []).map((x, i) => `${i + 1}. [${dec(x.category)}, ${x.difficulty}] ${dec(x.question)}\n   options: ${[...x.incorrect_answers, x.correct_answer].map(dec).sort().join(' / ')}\n   answer: ${dec(x.correct_answer)}`).join('\n') || 'no questions'; } },
  { name: 'draw_cards', group: F, taint: true, description: 'Draw cards from a fresh shuffled deck (Deck of Cards API).', input_schema: S({ n: int('cards, default 1, max 20') }),
    async run(env, { n }) { const r = await httpJson(env, `https://deckofcardsapi.com/api/deck/new/draw/?count=${capN(n, 1)}`); if (!r.ok) return errorText('draw_cards', r); return ((r.json || {}).cards || []).map(c => `${c.value} of ${c.suit}`).join(', ') || 'no cards'; } },
  { name: 'pokemon', group: F, taint: true, description: 'A Pokémon from PokéAPI: number, types, height, weight, base stats.', input_schema: S({ name: str('name or number') }, ['name']),
    async run(env, { name }) { const r = await httpJson(env, `https://pokeapi.co/api/v2/pokemon/${enc(String(name).trim().toLowerCase())}`, { cacheSeconds: 86400, maxBytes: 1024 * 1024 }); if (!r.ok) return errorText('pokemon', r); const p = r.json || {}; return `#${p.id} ${p.name}: ${(p.types || []).map(t => t.type.name).join('/')}, ${p.height / 10} m, ${p.weight / 10} kg. Stats: ${(p.stats || []).map(s => `${s.stat.name} ${s.base_stat}`).join(', ')}.`; } },
  { name: 'dnd', group: F, taint: true, description: 'D&D 5e reference (dnd5eapi): a spell, monster, class or equipment by name.', input_schema: S({ q: str('name, e.g. fireball, goblin, wizard, longsword') }, ['q']),
    async run(env, { q }) { const slug = String(q).trim().toLowerCase().replace(/[^a-z0-9]+/g, '-'); for (const kind of ['spells', 'monsters', 'classes', 'equipment']) { const r = await httpJson(env, `https://www.dnd5eapi.co/api/2014/${kind}/${enc(slug)}`, { cacheSeconds: 86400 }); if (r.ok && r.json && r.json.name) { const j = r.json; const desc = Array.isArray(j.desc) ? j.desc.join(' ') : (j.desc || ''); return `${j.name} (${kind.slice(0, -1)})${j.level != null ? `, level ${j.level}` : ''}${j.school ? `, ${j.school.name}` : ''}${j.challenge_rating != null ? `, CR ${j.challenge_rating}` : ''}${j.hit_points ? `, ${j.hit_points} hp` : ''}${j.hit_die ? `, hit die d${j.hit_die}` : ''}${j.cost ? `, ${j.cost.quantity} ${j.cost.unit}` : ''}. ${String(desc).slice(0, 400)}`; } } return `Nothing in the 5e SRD called ${q}.`; } },
  { name: 'mtg_card', group: F, taint: true, description: 'A Magic: The Gathering card from Scryfall: mana cost, type, text, set, price.', input_schema: S({ q: str('card name') }, ['q']),
    async run(env, { q }) { const r = await httpJson(env, `https://api.scryfall.com/cards/named?fuzzy=${enc(q)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('mtg_card', r); const c = r.json || {}; return `${c.name} ${c.mana_cost || ''} — ${c.type_line}. ${String(c.oracle_text || '').slice(0, 300)} (${c.set_name}, ${c.rarity}${c.prices && c.prices.usd ? `, $${c.prices.usd}` : ''}) ${c.scryfall_uri || ''}`; } },
  // ---- curiosities (Thor's shelf)
  { name: 'dad_joke', group: F, taint: true, description: 'A random dad joke.', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://icanhazdadjoke.com/', { headers: { accept: 'application/json' } }); return r.ok ? (r.json || {}).joke || 'no joke' : errorText('dad_joke', r); } },
  { name: 'joke', group: F, taint: true, description: 'A random safe joke (JokeAPI, safe-mode on).', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://v2.jokeapi.dev/joke/Any?safe-mode&type=single,twopart'); if (!r.ok) return errorText('joke', r); const j = r.json || {}; return j.type === 'twopart' ? `${j.setup}\n${j.delivery}` : j.joke || 'no joke'; } },
  { name: 'chuck_norris', group: F, taint: true, description: 'A random Chuck Norris fact.', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://api.chucknorris.io/jokes/random'); return r.ok ? (r.json || {}).value || 'no fact' : errorText('chuck_norris', r); } },
  { name: 'advice', group: F, taint: true, description: 'A random piece of advice (Advice Slip).', input_schema: S({}), async run(env) { const r = await httpJson(env, `https://api.adviceslip.com/advice?t=${Date.now()}`, { accept: 'application/json, text/plain' }); return r.ok ? ((r.json || {}).slip || {}).advice || 'no advice' : errorText('advice', r); } },
  { name: 'affirmation', group: F, taint: true, description: 'A short affirmation.', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://www.affirmations.dev/'); return r.ok ? (r.json || {}).affirmation || 'no affirmation' : errorText('affirmation', r); } },
  { name: 'quote', group: F, taint: true, description: 'A random quotation with its author (ZenQuotes).', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://zenquotes.io/api/random'); if (!r.ok) return errorText('quote', r); const q = (r.json || [])[0] || {}; return q.q ? `"${q.q}" — ${q.a}` : 'no quote'; } },
  { name: 'useless_fact', group: F, taint: true, description: 'A random useless fact.', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://uselessfacts.jsph.pl/api/v2/facts/random?language=en'); return r.ok ? (r.json || {}).text || 'no fact' : errorText('useless_fact', r); } },
  { name: 'yes_or_no', group: F, taint: true, description: 'A yes or no (or maybe), with a gif (yesno.wtf).', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://yesno.wtf/api'); return r.ok ? `${String((r.json || {}).answer || '').toUpperCase()} ${(r.json || {}).image || ''}` : errorText('yes_or_no', r); } },
  { name: 'random_dog', group: F, taint: true, description: 'A random dog picture URL (dog.ceo).', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://dog.ceo/api/breeds/image/random'); return r.ok ? (r.json || {}).message || 'no dog' : errorText('random_dog', r); } },
  { name: 'random_fox', group: F, taint: true, description: 'A random fox picture URL (randomfox.ca).', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://randomfox.ca/floof/'); return r.ok ? (r.json || {}).image || 'no fox' : errorText('random_fox', r); } },
  { name: 'random_cat', group: F, taint: true, description: 'A random cat picture URL (cataas).', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://cataas.com/cat?json=true'); if (!r.ok) return errorText('random_cat', r); const j = r.json || {}; return j.url ? (String(j.url).startsWith('http') ? j.url : `https://cataas.com${j.url}`) : (j._id ? `https://cataas.com/cat/${j._id}` : 'no cat'); } },
  { name: 'http_cat', group: F, taint: false, description: 'The http.cat picture for an HTTP status code.', input_schema: S({ code: int('status code, e.g. 404') }, ['code']), async run(env, { code }) { const c = Math.max(100, Math.min(599, Number(code) || 404)); return `https://http.cat/${c}`; } },
  { name: 'robot_avatar', group: F, taint: false, description: 'A robot avatar image URL for any text (RoboHash).', input_schema: S({ text: str('seed text') }, ['text']), async run(env, { text }) { return `https://robohash.org/${enc(String(text).slice(0, 80))}.png?size=200x200`; } },
  { name: 'pixel_avatar', group: F, taint: false, description: 'A pixel-art avatar image URL for a seed (DiceBear).', input_schema: S({ seed: str('seed text') }, ['seed']), async run(env, { seed }) { return `https://api.dicebear.com/9.x/pixel-art/svg?seed=${enc(String(seed).slice(0, 80))}`; } },
  { name: 'art_random', group: F, taint: true, description: 'A random public-domain artwork from the Art Institute of Chicago: title, artist, date, image.', input_schema: S({}), async run(env) { const page = 1 + Math.floor(Math.random() * 200); const r = await httpJson(env, `https://api.artic.edu/api/v1/artworks?page=${page}&limit=1&fields=title,artist_display,date_display,image_id,id&query[term][is_public_domain]=true`, { cacheSeconds: 0 }); if (!r.ok) return errorText('art_random', r); const a = ((r.json || {}).data || [])[0]; if (!a) return 'no artwork'; return `${a.title} — ${String(a.artist_display || '').split('\n')[0]} (${a.date_display || '?'})${a.image_id ? `\nhttps://www.artic.edu/iiif/2/${a.image_id}/full/843,/0/default.jpg` : ''}\nhttps://www.artic.edu/artworks/${a.id}`; } },
  { name: 'mcu_countdown', group: F, taint: true, description: 'Days until the next Marvel Cinematic Universe film (on theme).', input_schema: S({}), async run(env) { const r = await httpJson(env, 'https://www.whenisthenextmcufilm.com/api', { cacheSeconds: 3600 }); if (!r.ok) return errorText('mcu_countdown', r); const j = r.json || {}; return `${j.title} — ${j.days_until} days (${j.release_date}).${j.following_production ? ` Then ${j.following_production.title} on ${j.following_production.release_date}.` : ''}`; } },
  { name: 'is_even', group: F, taint: true, description: 'Is a number even? (Asks the isEven API, yes, really. Falls back to arithmetic.)', input_schema: S({ n: int('the number') }, ['n']), async run(env, { n }) { const v = Number(n); const r = await httpJson(env, `https://api.isevenapi.xyz/api/iseven/${enc(String(Math.trunc(v)))}/`); if (r.ok && r.json && typeof r.json.iseven === 'boolean') return `${v} is ${r.json.iseven ? 'even' : 'odd'}. (Confirmed by the isEven API. Yes, really.)`; return `${v} is ${Math.trunc(v) % 2 === 0 ? 'even' : 'odd'} (the API was unavailable; arithmetic agrees).`; } },
  { name: 'xkcd', group: F, taint: true, description: 'The latest xkcd comic, or one by number.', input_schema: S({ num: int('comic number, optional') }), async run(env, { num }) { const r = await httpJson(env, num ? `https://xkcd.com/${Number(num)}/info.0.json` : 'https://xkcd.com/info.0.json', { cacheSeconds: 3600 }); if (!r.ok) return errorText('xkcd', r); const j = r.json || {}; return `xkcd #${j.num}: ${j.title} — ${j.alt}\n${j.img}`; } },
  { name: 'meme_templates', group: F, taint: true, description: 'Popular meme templates from Imgflip (names and blank image links).', input_schema: S({ n: int('templates, default 5, max 20') }), async run(env, { n }) { const r = await httpJson(env, 'https://api.imgflip.com/get_memes', { cacheSeconds: 86400 }); if (!r.ok) return errorText('meme_templates', r); return (((r.json || {}).data || {}).memes || []).slice(0, capN(n, 5)).map(m => `- ${m.name}: ${m.url}`).join('\n') || 'no templates'; } },
  { name: 'star_wars', group: F, taint: true, description: 'Star Wars reference (SWAPI mirror): a character, planet, starship or film by name.', input_schema: S({ q: str('name') }, ['q']), async run(env, { q }) { for (const kind of ['people', 'planets', 'starships', 'films']) { const r = await httpJson(env, `https://swapi.info/api/${kind}`, { cacheSeconds: 86400, maxBytes: 1024 * 1024 }); if (!r.ok) continue; const list = Array.isArray(r.json) ? r.json : ((r.json || {}).results || []); const hit = list.find(x => String(x.name || x.title || '').toLowerCase().includes(String(q).toLowerCase())); if (hit) { const drop = ['url', 'created', 'edited', 'films', 'residents', 'pilots', 'characters', 'planets', 'starships', 'vehicles', 'species', 'homeworld', 'opening_crawl']; return `${hit.name || hit.title} (${{ people: 'person', planets: 'planet', starships: 'starship', films: 'film' }[kind]}): ` + Object.entries(hit).filter(([k, v]) => !drop.includes(k) && typeof v !== 'object').map(([k, v]) => `${k.replace(/_/g, ' ')} ${v}`).join(', ').slice(0, 500); } } return `Nothing in the SWAPI called ${q}.`; } },
  { name: 'star_trek', group: F, taint: true, description: 'Star Trek reference (STAPI): a character by name.', input_schema: S({ q: str('character name') }, ['q']), async run(env, { q }) { const r = await httpFetch(env, 'https://stapi.co/api/v1/rest/character/search', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: `name=${enc(q)}&pageSize=5`, accept: 'application/json' }); if (!r.ok || !r.json) return errorText('star_trek', r.ok ? { error: 'not JSON' } : r); const all = (r.json || {}).characters || []; const ql = String(q).toLowerCase(); const c = all.find(x => String(x.name || '').toLowerCase().split(/\s+/).includes(ql)) || all.find(x => String(x.name || '').toLowerCase().includes(ql)) || all[0]; if (!c) return `No character called ${q} in STAPI.`; return `${c.name}${c.gender ? ` (${c.gender})` : ''}${c.yearOfBirth ? `, born ${c.yearOfBirth}` : ''}${c.placeOfBirth ? ` in ${c.placeOfBirth}` : ''}. ${['hologram', 'fictionalCharacter', 'mirror', 'alternateReality'].filter(k => c[k]).join(', ')} https://stapi.co/character/${c.uid}`; } },
  { name: 'rick_and_morty', group: F, taint: true, description: 'A Rick and Morty character by name (status, species, origin, location).', input_schema: S({ q: str('character name') }, ['q']), async run(env, { q }) { const r = await httpJson(env, `https://rickandmortyapi.com/api/character/?name=${enc(q)}`, { cacheSeconds: 86400 }); if (!r.ok) return errorText('rick_and_morty', r); const c = ((r.json || {}).results || [])[0]; if (!c) return `No character called ${q}.`; return `${c.name}: ${c.status}, ${c.species}${c.type ? ` (${c.type})` : ''}, from ${(c.origin || {}).name}, last seen ${(c.location || {}).name}. ${c.image}`; } }
];
